### ISSUE TITLE
Please add Sir Thirsty to peerage map

### ISSUE THREAD

**Issue by dbolli** [NoAgenda/peerage#10]
Please add me :)

1. Derek Bolli aka Sir Thirsty
2. [ no protectorate ] Location Lower Hutt, Wellington, New Zealand (was North Sydney, NSW, Australia at date of knighting)
3. https://noagendaplayer.com/shows/539 at 02hrs25min15sec

#ITM

Many thanks in advance,
Derek.

**Comment by bdougherty** [comment]
TYFYC, Sir Thirsty. Only Baron level and above are able to claim protectorates and be on the map. 539 was quite a long time ago, have you had a title change since then?

**Comment by dbolli** [comment]
No problem, I am still on my way to Baronet :)

Can I suggest that it would be nice to see the name of the Baron(ess)
by hovering mouse over the various protectorates?

TYFYC and #ITM

**Comment by bdougherty** [comment]
@dbolli you should be able to click on each area to see whose protectorate it is

**Comment by bdougherty** [comment]
Closing this issue, but please let me know when you reach Baron!

**Comment by dbolli** [comment]
Thanks for your help :)

The peerage info does appear if you keep clicking around the centre of the region.

TYFYC,
Derek.
