### ISSUE TITLE
Add Sir John the Brewer, Baron of the Bay

### ISSUE THREAD

**Issue by brewvet** [NoAgenda/peerage#11]
Sir John the Brewer, Baron of the Bay
Bay of St Louis, MS
Title change Ep 1052 http://naplay.it/1052/2:46:35

![barony](https://user-images.githubusercontent.com/15810008/55797985-61dbd500-5a93-11e9-8bf4-e2db33179296.PNG)

Thank you for your courage!

**Comment by bdougherty** [comment]
Thanks, Sir John. This will take me a little bit of extra time because I have to draw the shape manually.

**Comment by brewvet** [comment]
Not a problem, Sir (?) Brad. It ain’t got to be exact. I noticed some other issues with geojson (maybe?) files. If there is a primer on the format somewhere  I can probably figure it out and save you some time and trouble. 

--
John J. Hornor | KG5ZFA
http://www.hornor.net
