### ISSUE TITLE
Sir Gene Update

### ISSUE THREAD

**Issue by genen** [NoAgenda/peerage#12]
Adam and John perpetually screw up my protectorates... both seem to take pleasure in it!

My TOP title is Duke - Was 'of the south' when I was the 3rd duke in the US, but I have voluntarily shrunk my territory to the territory of the old Republic of Texas.  (google it)

Great use of github btw!

**Comment by bdougherty** [comment]
Just to confirm before I make the change, is this the correct map?

![Old Republic of Texas map](https://user-images.githubusercontent.com/15747/55846956-8f696280-5b15-11e9-8887-da922cc162d8.png)

**Comment by genen** [comment]
That’s the one! Also I noticed you don’t have Grand Duke Melancon listed as such. He should have the pacific NW.  I didn’t even know about this site till Adam mentioned it so I’m sure other dukes have not reached out to you to clarify yet.


Gene

**Comment by bdougherty** [comment]
@genen what do you want your full title to be? Going to make it "Protectorate of Sir Gene Naftulyev, Duke of the Republic of Texas" unless you want something else.

**Comment by genen** [comment]
Ya that’s fine… I will always be Sheriff of Tx to Adam… which is not a real thing…. Lol

**Comment by genen** [comment]
Just checked map today, no update on title or region yet?
