### ISSUE TITLE
Peerage map request: Peterborough Ontario Canada

### ISSUE THREAD

**Issue by rdolishny** [NoAgenda/peerage#18]
1. Sir Richard Knight of the Kawarthas
2. 50km circumference around Peterborough, Ontario Canada
3. First week of August, 2017. 952 probably.

**Comment by rdolishny** [comment]
Confirmed! Show 952. http://adam.curry.com/html/NoAgendaEpisode952iC-1501789510.html

**Comment by bdougherty** [comment]
TYFYC, Sir Richard. Only Baron level and above can request a territory. That was awhile ago, have you been upgraded since then?

**Comment by rdolishny** [comment]
Oh no that's fine thanks for the update. Just a regular old sir.
